### PR TITLE
1.0.0

### PR DESCRIPTION
**Pull request by karellm**
## Roadmap for the release:

- [x] Rewrite helpers
- [x] Write a Lexer per supported language
  - [x] HTML
  - [x] Handlebars
  - [x] JS
- [x] Write a parser that auto-detect the file extension and call the proper Lexer
- [x] Update CLI code
  - [x] Transition to `vinyl-fs`
  - [x] Compile ES6 code
  - [x] Test cli
- [x] Bugs and other
  - [x] Make sorting an option #74 
  - [x] Make indentation an option #75 
  - [x] Remove `gulp-util`
  - [x] Update lexers options
  - [x] Fix defaultValue bug #43 
  - [x] colon in key #67
  - [x] Better error handling ([PluginError](https://github.com/gulpjs/plugin-error)?)
  - [x] YAML output #61 
  - [x] Create context keys ([see this](https://github.com/i18next/i18next-parser/blob/master/index.js#L124)) 
- [x] Update the documentation
  - [x] CLI
  - [x] Gulp
  - [x] Write transition document

## Roadmap post release:

- [ ] Track file path #55 
- [ ] Write a Lexer for JSX #57 
- [ ] Add documentation Grunt/Webpack
- [ ] Handle [arrays/objects](https://www.i18next.com/objects-and-arrays.html) in catalog
- [ ] `useKeyAsDefaultValue`

## Other

- [x] ~[Prettier](https://github.com/prettier/prettier)~
- [ ] [Coveralls](https://coveralls.io/)

### CODE REVIEW

**Comment by birdy-** [comment]
Since you rewrite many things, take a look at prettier. It's a great tool to clean up code. Just add `.prettierrc` and use their binary or VSCode/Atom plugin.

**Comment by karellm** [comment]
@birdy- thanks I will definitely look at it. My code style changed quite a bit in the last 4 years, every time I had to maintain that code base was an humbling moment 😄 The new structure will hopefully make that a lot more pleasant. 

As to opinionated code styles, they make sense until they don't and then get in the way. That said I definitely should configure a linter of sort for collaborators to know what rules to follow.

**Comment by tkrotoff** [comment]
I have a suggestion: generating JS files (e.g `locales/fr/translation.js`). We would then have comments:
```JS
{
  // Extracted from file src/utils/Colors.js
  "Red": "Rouge",
  "Orange": "Orange",
  "Yellow": "Jaune",
  "Green": "Vert",
  "Blue": "Bleu",
  "Indigo": "Indigo",
  "Violet": "Violet",

  // Extracted from file src/utils/Languages.js
  "English": "Anglais",
  "French": "Français",

  // Extracted from file src/SignUpForm.js
  "First Name": "Prénom",
  "Last Name": "Nom de famille",
  "Email": "Email"
}
```

It's nice for the translator to have the "context", like [gettext's PO files](https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html):
```PO
#: lib/error.c:116
msgid "Unknown system error"
msgstr "Error desconegut del sistema"
```

**Comment by karellm** [comment]
@tkrotoff My understanding is that #55 would address that. Is there something more you'd want?

**Comment by tkrotoff** [comment]
@karellm thx for the link. #55 proposes to use JSON, that's better than my proposition that relies on JS comments: you can then easily extract `paths` with a tool if needed.

**Comment by birdy-** [comment]
Prettier will format code with few option (max length of a line, simple/double quote, ...). It's great because you don't have to do it manually.
Prettier is not a `eslint --fix` because it won't change anything in your code. It means, if you use a `let` instead of a `const` or do some useless import, it won't change it.
So prettier is not "enough", you have to use a lint. Since `airbnb-eslint` is not "compatible" with prettier out of the box, you can extend your rules with `airbnb` and `prettier` to solve incompatibilities. https://github.com/prettier/prettier-eslint

If you need help or you want me to setup it, I can do it.

**Comment by karellm** [comment]
It's almost there. `1.0.0-beta1` is coming very soon!

**Comment by karellm** [comment]
@birdy- I won'd use prettier because it transforms:

```
if() {
}
else {
}
```

into

```
if() {
} else {
}
``` 

which makes absolutely no sense to me.

**Comment by birdy-** [comment]
> By far the biggest reason for adopting Prettier is to stop all the on-going debates over styles.
:D

**Comment by karellm** [comment]
Well there is something more important than rigidity. It's consistency, readability and actual productivity while coding. Prettier doesn't score well in 2 of the 3 for me.

**Pull request merged**
