### PR TITLE
Sort keys at the end of flush

### PR DESCRIPTION
**Pull request by trew**
### Why am I submitting this PR

Ensures that special keys such as plural or context keys are sorted instead of appearing at the bottom.

### Does it fix an existing ticket?

Yes #169 (and maybe #400 ?)

### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] tests are included and pass (see [details here](https://github.com/i18next/i18next-parser/blob/master/docs/development.md#tests))
- [x] documentation is changed or added
- [x] I ran `yarn build` to compile and prettify the code

### CODE REVIEW

**Comment by trew** [comment]
> Just letting you know that #423 might have significant impact on this

Doesn't look like there are significant code changes that conflict. Tests maybe. Either way I really want v4 PR to be merged as well.

**Comment by karellm** [comment]
@trew The PR looks good. I want to merge #423 into master and then we will be able to rebase this PR and update the tests.

**Comment by Elindorath** [comment]
> > Just letting you know that #423 might have significant impact on this
> 
> Doesn't look like there are significant code changes that conflict. Tests maybe. Either way I really want v4 PR to be merged as well.

@trew I wasn't referring so much to conflicts as to how sorting should order plural keys
```json5
// From https://www.i18next.com/misc/json-format#i-18-next-json-v4
{
  "keyPluralMultipleEgArabic_zero": "the plural form 0",
  "keyPluralMultipleEgArabic_one": "the plural form 1",
  "keyPluralMultipleEgArabic_two": "the plural form 2",
  "keyPluralMultipleEgArabic_few": "the plural form 3",
  "keyPluralMultipleEgArabic_many": "the plural form 4",
  "keyPluralMultipleEgArabic_other": "the plural form 5",
}
```
As this is not an alphanumeric order, the [`sort-keys`](https://github.com/sindresorhus/sort-keys) package could not handle this

**Comment by trew** [comment]
@Elindorath that's correct, this PR isn't perfect, but it's better than having the keys end up far away from the associated key, which is the main point of this PR. I welcome a different solution though, but I don't see an issue with merging this in the meantime.

**Comment by trew** [comment]
Rebased on latest master.

**Comment by trew** [comment]
Closing this in favor of #438

**Pull request closed without merging**
