### PR TITLE
Extract translation from comment for both Javascript and Jsx Lexers

### PR DESCRIPTION
**Pull request by tienpham94**
### Why am I submitting this PR
Adds support for extracting translations from comments for both JavascriptLexer and JsxLexer
Fixes https://github.com/i18next/i18next-parser/issues/166

This PR is an extension of https://github.com/i18next/i18next-parser/pull/222 and is to be merged after https://github.com/i18next/i18next-parser/pull/222. In https://github.com/i18next/i18next-parser/pull/222 the JavascriptLexer is extended to add support for extracting translations from comments. This PR extends it and adds the same support for JsxLexer.

I wanted to add comment extraction support to JsxLexer few days ago. Before seeing @vincaslt 's PR, I went with a quite similar approach to support parsing comments in JsxLexer. You can check the approach in this commit https://github.com/i18next/i18next-parser/commit/3337bb2428b480112fdbf344cc6aab0d640be5c4 if you are interested, but my approach only handles single line comment, @vincaslt 's approach is more extensive that it handles also multiline comment, so I switched to using his approach.

```js
// My initial approach
const sourceFile = ts.createSourceFile(
      filename,
      content,
      ts.ScriptTarget.Latest
    )
const comments = ts.getLeadingCommentRanges(
        sourceFile.getText(),
        node.getFullStart()
      )
 if (comments) {
     comments.map((comment) => {
         const commentEntry = sourceFile
            .getFullText()
            .slice(comment.pos, comment.end)

           if (comment.kind === ts.SyntaxKind.SingleLineCommentTrivia) {
            const regExp = / t\(([^)]+)\)/
            var matches = regExp.exec(commentEntry)
            if (matches) {
              const key = matches[1].replace(/['"\\]+/g, '')
              keys.push({ key })
            }
          }
    })
}

```
### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] tests are included and pass for jsx-lexer.test.js

### CODE REVIEW

**Comment by vincaslt** [comment]
Good catch, I thought JS lexer would implicitly handle this for Jsx too, but I didn't bother to make sure... I guess ideally it would reuse the same logic, since it seems pretty similar. As an idea - something like a closure in JS lexer which would keep visited comments' state, that Jsx lexer can reuse:

```
  createCommentNodeParser(node) {
    const visitedComments = new Set()
    const keys = []

    return () => {
      s.forEachLeadingCommentRange(
        ...
      )
    }
  }

extract(content, filename = '__default.js') {
    const parseCommentNode = this.createCommentNodeParser.call(this, node)

    const parseTree = (node) => {
      let entry

      parseCommentNode(node)
      ...
    }
  }
```

**Comment by karellm** [comment]
@tienpham94 Thanks for the PR!

@vincaslt I like your suggestion, I'll let you review the code and let me know when it's ready to merge and publish.

**Comment by tienpham94** [comment]
@vincaslt Updated based on your comment!

**Comment by karellm** [comment]
Published as `2.1.1`

**Comment by arsalansufi** [comment]
Nice! I noticed this issue for the first time today as I was adding a comment to a `.tsx` file and it wasn't getting added to my catalog (I was on v2.1.0). Amazing this this fix was rolled out just yesterday. Thanks!

**Pull request merged**
