### PR TITLE
Add support for keepRemovedPatterns option - closes #693

### LINKED ISSUE #693: Add a config to keep some dynamic keys
## 🚀 Feature Proposal

Add an option so that `i18next-parser` keeps some of the keys that are in the translation files but are not extracted from the code.

## Motivation

When using dynamic keys or dynamic contexts, there are multiple reasons for adding some keys that would be used at runtime while not easy to extract from the code statically. I'd like to be able to use `i18next-parser` to get all the other keys right, but trust me on the keys that I've added myself to the translation files.

As of v7, I only have the choice to either keep all existing translations (`keepRemoved` option) or delete all the ones that `i18next-parser` cannot extract from the code. I'd like to have another option and list patterns for which I want to keep the translations that exist.

## Example

Given the following code (using React):
```tsx
  const {t} = useTranslation()
  return <p>
    {t('pickACountryQuestion')}
    <select>
     {countries.map(countryId => <option value={countryId}>{t(`countryName.${countryId}`)}</option>)}
    </select>
  </p>
```

Adding this in the `i18next-parser.config.js`:
```js
module.exports = {
  keepRemovedPatterns: [
    /^translation:countryName\.\w+/,
  ]
}
```

I'd like to keep all the `countryName` sub tree containing something like:
```json
  "countryName": {

    "BDI": "Burundi",
    "BEL": "Belgium",
    "BEN": "Benin",

  }
```
while still removing other keys not used in my code.

### PR DESCRIPTION
**Pull request by pcorpet**
### Why am I submitting this PR

To add a new option discussed in #693.

### Does it fix an existing ticket?

Yes #693 

### Checklist

- [X] only relevant code is changed (make a diff before you submit the PR)
- [X] tests are included and pass: `yarn test` (see [details here](https://github.com/i18next/i18next-parser/blob/master/docs/development.md#tests))
- [x] documentation is changed or added

### CODE REVIEW

**Comment by pcorpet** [comment]
@karellm can you help me push this one further please?

**Comment by pcorpet** [comment]
Up. @karellm in the issue you wrote that you would review a PR to implement this, can you take a look please?

**Comment by karellm** [comment]
@pcorpet It looks good to me, here 2 comments:

1. I believe I would prefer not to add the `keepRemovedPatterns` and allow `keepRemove` to accept an array of patterns. The main reason is that otherwise, it's not clear which take precedence of the other. What do you think?
2. Can you please rebase from master?

**Comment by jialinyang-ms** [comment]
@pcorpet @karellm Really appreciate the work you folks put into proposing this feature and creating the PR. Have you had any updates on it? It would be great if we could get this feature implemented.

**Comment by karellm** [comment]
@jialinyang-ms  Feel free to take over the PR if you want to take my comments into consideration. I have limited bandwidth to code on this myself but I will review PRs.

**Comment by josx** [comment]
i am also needing this feature for my project, would be great if someone can finnish @pcorpet work.

**Comment by pcorpet** [comment]
@karellm I've implemented your suggestion, please take another look. (Sorry for the lag and thanks @josx for pinging again, that pushed me to update).

**Comment by karellm** [comment]
Thanks for the updates! It is deployed as `8.2.0`

**Pull request merged**
