### PR TITLE
enable all tests again

### PR DESCRIPTION
**Pull request by nickasd**
This enables all tests again, some of them failing.

### CODE REVIEW

**Comment by nickasd** [comment]
I got a crash when my html files contained keys like `one` and `one.two` both mapped to a string. This fix overwrites any object that might be contained in the existing map, i.e. replacing the subtree of `one` with the new string or the string of `one` with the new subtree.

**Comment by karellm** [comment]
@nickasd This is non fast-forward at this point. I'm also confused as to why you would have both in your file? `i18next` doesn't support that AFAIK.

**Comment by nickasd** [comment]
In my case because of a user error. This kind of error is also logged as a conflict.

**Comment by nickasd** [comment]
Shall I try to resolve the conflicts again?

**Comment by karellm** [comment]
@nickasd If you need this and want to move to `1.0.0` then yes :) I would just invite you to add a better description and title because it doesn't represent the content of the PR anymore. Or you can close this and reopen one.

**Comment by nickasd** [comment]
I opened a new PR #202 .

**Pull request closed without merging**
