### PR TITLE
Move JS to acorn parsing

### PR DESCRIPTION
**Pull request by karellm**
- [x] Move JS parsing to acorn
- [ ] Move React parsing to acorn

### CODE REVIEW

**Comment by karellm** [comment]
@MynockSpit Would you mind giving me a hand here? I'm not personally using react and did all the work for JS. Moving to the `acorn-jsx` parser per your suggestion would be a nice addition.

**Comment by MynockSpit** [comment]
Sure, I can take a look.

**Comment by MynockSpit** [comment]
I think it makes sense to combine the JS and JSX parsers -- the JSX parser is essentially an optional path on the JS parser. (If we're parsing a .jsx file without JSX, the JSX path will never get hit, and if we parse a .js file with JSX, the JSX path will get hit. It'll parse it correctly either way.)

Thoughts?

**Comment by karellm** [comment]
@MynockSpit I tend to prefer two lexers in cases there would be differences later on. But I'm totally ok the React lexer to inherit the Javascript one instead of the HTML one.

I trust your judgement though as you dive into `acorn-jsx`. If it works seamlessly and it doesn't add too much complexity it might be ok to combine them.

**Comment by MynockSpit** [comment]
Cool. I'll make a PR with them merged and comments (and pros/cons) and see what you think.

**Comment by MynockSpit** [comment]
Let me know what you think: https://github.com/i18next/i18next-parser/pull/93

**Pull request merged**
