### PR TITLE
Support unicode escape sequence in json

### PR DESCRIPTION
**Pull request by Elindorath**
### Why am I submitting this PR

When using unicode escape sequences, the parser converts them to utf8. This PR should allow to preserve them.

Be aware that this PR will also convert all non-ASCII characters to its unicode escape sequences as well. Personally, I find it best to make these characters explicit, but let me know if you'd like to see this behavior as an option.
Moreover, note that the case is not preserved inside the unicode escape sequences, it will always be lowercased (`\u00A0` will become `\u00a0`).

### Does it fix an existing ticket?

Yes #361 

### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] tests are included and pass (see [details here](https://github.com/i18next/i18next-parser/blob/master/docs/development.md#tests))
- [ ] documentation is changed or added
- [x] I ran `yarn build` to compile and prettify the code

### CODE REVIEW

**Comment by karellm** [comment]
Sorry for the late answer, I had missed this one. Thanks for the PR!

**Comment by kobrynsky** [comment]
Hi there!
shouldn't it be optional parameter? In my case I would like to have no escaped characters.

It currently converts it from this:
image
to this:
image

To work as I want it to work i commented code from this pull request:
image

But there is a possibility that I don't fully understand how I should handle it xD

I can make pull request in my free time to make this optional if you would accept it 😄 

Either way, this package is awesome. Thank you for your work.

**Comment by damien-monni** [comment]
+1 on making this optional. My JSON file for french translation is unreadable now, so I have to stick with v4.2.0. 😅

image

**Comment by karellm** [comment]
That's indeed a negligence on my part, I should have better tested this before merging the PR. I'm not sure if it should be optional or handled differently altogether. I will look into it later today and keep you posted.

**Comment by Vovan-VE** [comment]
Forced escapes made cyrillic translation files to consist of escapes for about 99%, and so made files completely not user-friendly. This feature either should be optional or it should be in next major version as BC break feature.

**Comment by Vovan-VE** [comment]
Probably, unicode properties `\p{...}` should be used at least to achieve original #361 goal.

**Comment by bodryi** [comment]
Good day!
Tried to use this library today. All Latin characters are extracted correctly, but all Cyrillic ones are converted to Unicode escaped values. Had no idea why this happens, but then I looked source code and found, that changes were made in this PR.

Looking forward for this issue to be solved!

image_2021-08-03_13-44-55

**Comment by Vovan-VE** [comment]
@bodryi , this issue was introduced in `4.3.0`, so you can use version `~4.2`.

**Comment by bodryi** [comment]
Already downgraded version to 4.2.0 and it worked like a charm.

@Vovan-VE, thanks for advice!

**Comment by karellm** [comment]
@Elindorath After looking a little more into this issue, I don't think this PR should make it to this project. I understand you case for preserving unicode escape sequence and if you want to submit a PR that does just that, I will look at it!

Everyone else, `4.4.0` is back on track!

**Pull request merged**
