### PR TITLE
Added withNamespaces support

### PR DESCRIPTION
**Pull request by dcworldwide**
Tests passing. 
Testing deploying to npm and using in my setup as well.

### CODE REVIEW

**Comment by dcworldwide** [comment]
LGTM

**Comment by karellm** [comment]
Are you trolling here or do you honestly don't understand my question? How does `LGTM` answer my question?

**Comment by dcworldwide** [comment]
It means read between the lines because an explanation isnt required. Look at the diff between the pr commits and you will have your answer. It is a very simple change. Its tested. It does not need docs

**Comment by karellm** [comment]
Well how about you read my comments and apply them? You closed a PR and reopen one with the exact same problems in it... So don't read between the lines, read the lines and address them. I'm tired of your attitude, I'm not here to read your mind, be clear, be verbose if needed.

**Comment by karellm** [comment]
Closing this, when you are ready to address the comments in #131 and #132 feel free to reopen with the changes.

**Pull request closed without merging**
