### PR TITLE
Feature/vue lexer

### PR DESCRIPTION
**Pull request by newbie78**
i'msorry, i'm forget to commit the compiled (dist) files.

### CODE REVIEW

**Comment by karellm** [comment]
Is this not working in `1.0.0`? I believe I did compile the code after I merged it.

**Comment by newbie78** [comment]
i'm build this on 1.0.0-beta37. what do I need to do to get my pr confirmed?

**Comment by karellm** [comment]
@newbie78 Have you tried `1.0.0` ? You don't need to use the `beta37` or any other beta anymore.

**Comment by newbie78** [comment]
> @newbie78 Have you tried `1.0.0` ? You don't need to use the `beta37` or any other beta anymore.

yes. all working fine! thnx

**Pull request closed without merging**
