### PR TITLE
Fix tests on Windows

### PR DESCRIPTION
**Pull request by TheDancingCode**
This PR normalizes file paths in the tests to make the tests pass on Windows.

### CODE REVIEW

**Comment by karellm** [comment]
Hi, I'm a little confused by this PR.`path.normalize('en/test_plural.json')` will return exactly `en/test_plural.json`. Can you describe the issue you're having and the solution you found? 

I'm closing this, not by lack of interest but because `master` changed so much that a new PR might make more sense at this point.

**Comment by TheDancingCode** [comment]
Paths on Windows have a different segment separator: `\` instead of `/`. Because of this, expressions like `file.relative === 'en/test_plural.json'` will return `false`, since `file.relative` equals `'en\test_plural.json'` on Windows. A simple fix is to normalize the path; an operation that will indeed return `'en/test_plural.json'` on your system, but `'en\test_plural.json'` on Windows systems, like mine. Another way to achieve this is to use `path.join('en', 'test_plural.json')`.

This is fixing a problem that you don't have, but that Windows users face.

**Comment by karellm** [comment]
Thanks for the clarification. I will fix the test on master branch since `1.0.0-beta` changed the code base a lot!

**Comment by karellm** [comment]
@TheDancingCode I fixed them but have no way to test. I would appreciate if you could have a look: https://github.com/i18next/i18next-parser/commit/96a49aa0e098cad995c75049564f57ebbc1ada35

Thanks for your contribution!

**Pull request closed without merging**
