### PR TITLE
Add parsing of context in option of translation function

### PR DESCRIPTION
**Pull request by birdy-**
- Regex has been updated to match options
- If a `context` is found, it will define key as `key_context`
- add param to change context separator (`_` by default)

Solves https://github.com/i18next/i18next-parser/issues/46

### CODE REVIEW

**Comment by birdy-** [comment]
Somebody here ? :)

**Comment by karellm** [comment]
Been busy but I will review this later today 👍

**Comment by birdy-** [comment]
Yes ! And see the other PR ;)

**Comment by karellm** [comment]
@birdy- You are making me review the only part I always pray people don't make a PR about... regexes 😢 

It should be released soon, I'm reviewing it now.

**Comment by karellm** [comment]
@birdy- I really like how you used the ungready operator 👍 

My only concern is that the way you parse the object, the `context` has to be the last key. Can the object take other attributes?

**Comment by karellm** [comment]
`0.10.0` was just released

**Comment by birdy-** [comment]
Yes, I should fix that. I think it can be solved easily

**Comment by birdy-** [comment]
And thanks for merge(s) btw :)

**Comment by birdy-** [comment]
Oh you already fixed it ;) Ty :)

**Pull request closed without merging**
