### PR TITLE
fix: added support for string arrays as an argument to the useTranslation

### PR DESCRIPTION
**Pull request by sarakusha**
### Why am I submitting this PR

added support for string arrays as an argument to the useTranslation

### Does it fix an existing ticket?

Yes/No #305

### Checklist

- [ ] only relevant code is changed (make a diff before you submit the PR)
- [ ] tests are included and pass (see [details here](https://github.com/i18next/i18next-parser/blob/master/docs/development.md#tests))
- [ ] documentation is changed or added
- [ ] I ran `yarn build` to compile and prettify the code

### CODE REVIEW

**Comment by CarrotIronfoundersson** [comment]
This fix indeed solves the issue with array of namespaces as argument for useTranslation hook. I applied the change manually and tested it my project environment!

**Comment by AlphaByte02** [comment]
This resolve also the #220 that was lost.

You probably need to add the test case for this PR to be valid and also is a good thing for the future.

**Comment by karellm** [comment]
@sarakusha Thanks for the PR, can you please add a test to document this change? It is a requirement for me to merge a PR.

**Comment by simonasdev** [comment]
would also love this feature

**Comment by sarakusha** [comment]
> @sarakusha Thanks for the PR, can you please add a test to document this change? It is a requirement for me to merge a PR.

Actually, I practically didn’t do anything new. When I wanted to add functionality, it turned out that everything was implemented for `withTranslation`. I just changed the condition so that it all worked for `useTranslation`

**Comment by karellm** [comment]
@sarakusha I understand but maybe the feature wasn't properly tested before. It doesn't hurt to add a test, see it as a way to document the change.

**Comment by sarakusha** [comment]
I looked at how the parser works and found that it does not know how to handle constructs like `t("namespace:key")`, but it recognizes `t("key", { ns: namespace })`
I will create a new PR

**Comment by sarakusha** [comment]
I had to add the passing of `options` from the `Parser` to `Lexer`, since the namespace separator is set in the `Transform` and passed to the `Parser`, but there was no way to get it in the `Lexer`

**Comment by karellm** [comment]
@sarakusha I don't think this logic belongs in the Lexer. The Lexer is only extracting keys (whether it contains a namespace or not). Then the transform is in charge of making sense what is in the key. You can see the code here: https://github.com/i18next/i18next-parser/blob/master/src/transform.js#L103

That's the reason why Lexers don't need to know about the `namespaceSeparator`, it's not their concern. If you want to test for namespace handling, it should happen at the parser level, not the lexer level.

**Comment by karellm** [comment]
Thanks. Deployed as `4.6.0`

**Pull request merged**
